services:
  server:
    container_name: mcserver
    build: .
    restart: unless-stopped    
    ports:
      - 25565:25565/tcp
      - 25565:25565/udp
    networks:
      - default-nat
  mysql:
    container_name: mcserver_dynmapdb
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password123!
    networks:
      - default-nat
networks:
  default-nat: